version: '3.9'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    volumes:
      - ./rabbitmqconf/:/etc/rabbitmq/:ro
    ports:
      - '5672:5672'
      - '15672:15672'
