version: '3.9'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:      
      - type: bind
        source: ./rabbitmq/
        target: /etc/rabbitmq/